import { AlertTriangle, ArrowRight, Check, ChevronRight, CircleDot, FileSearch, LockKeyhole, Play, ShieldCheck, Sparkles, X } from 'lucide-react'
import type { Action, Approval, AuditEvent, Evidence, IncidentSummary, Investigation, PolicyDecision, Transition } from './api'

export const formatMinorCurrency = (amount: number | null, currency = 'INR') => {
  if (amount === null) return '—'
  if (!Number.isSafeInteger(amount)) return 'Invalid amount'
  const minor = BigInt(amount)
  const major = minor / 100n
  const fraction = (minor % 100n).toString().padStart(2, '0')
  const majorText = major.toString()
  const grouped = currency === 'INR' ? majorText.replace(/(\d+)(\d{3})$/, '$1,$2').replace(/(\d+)(\d{2})(,\d{3})$/, '$1,$2$3') : majorText.replace(/\B(?=(\d{3})+(?!\d))/g, ',')
  return currency === 'INR' ? `₹${grouped}` : `${currency} ${grouped}.${fraction}`
}
export const formatMoney = formatMinorCurrency
export const rawMinorLabel = (amount: number | null) => amount === null ? 'No minor-unit value' : `${amount.toLocaleString('en-IN')} minor units`
export const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : '—'
export const titleCase = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/(^| )\w/g, (match) => match.toUpperCase())

export function MetricCard({ label, value, note, tone = 'neutral' }: { label: string; value: string | number; note?: string; tone?: 'neutral' | 'danger' | 'accent' | 'success' }) {
  return <article className={`metric-card ${tone}`}><span className="metric-label">{label}</span><strong>{value}</strong>{note && <span className="metric-note">{note}</span>}</article>
}
export function SeverityBadge({ value }: { value: string }) { return <span className={`badge severity-${value.toLowerCase()}`}><span className="badge-dot" />{value}</span> }
export function StatusBadge({ value }: { value: string }) { return <span className={`badge status-${value.toLowerCase()}`}>{titleCase(value)}</span> }
export function LoadingState({ label = 'Loading operational data' }: { label?: string }) { return <div className="state-panel"><span className="loader" /><p>{label}</p></div> }
export function ErrorState({ message }: { message: string }) { return <div className="state-panel error-state"><AlertTriangle size={20} /><p>{message}</p></div> }
export function EmptyState({ label }: { label: string }) { return <div className="state-panel"><FileSearch size={22} /><p>{label}</p></div> }

export function IncidentRow({ incident, onClick }: { incident: IncidentSummary; onClick: () => void }) {
  return <button className="incident-row" onClick={onClick}><div><strong>{incident.incident_code}</strong><span>{incident.title}</span></div><span className="row-type">{titleCase(incident.incident_type)}</span><SeverityBadge value={incident.severity} /><StatusBadge value={incident.status} /><span className="row-money">{formatMoney(incident.financial_exposure, incident.currency ?? 'INR')}</span><ChevronRight size={17} /></button>
}
export function EvidenceCard({ evidence }: { evidence: Evidence }) { return <div className="evidence-card"><div className="evidence-icon"><FileSearch size={17} /></div><div><strong>{evidence.entity_type}</strong><span>{evidence.relationship}</span><code>{evidence.entity_id}</code></div><time>{formatDate(evidence.created_at)}</time></div> }
export function WorkflowRail({ active = 'INVESTIGATE' }: { active?: string }) { const steps = ['OBSERVE', 'DETECT', 'INVESTIGATE', 'DECIDE', 'APPROVE', 'EXECUTE', 'VERIFY', 'RESOLVE']; return <div className="workflow-rail">{steps.map((step, index) => <div className={`workflow-step ${step === active ? 'active' : ''}`} key={step}><span>{index + 1}</span>{step}{index < steps.length - 1 && <ArrowRight size={13} />}</div>)}</div> }
export function IncidentTimeline({ incident }: { incident: IncidentSummary }) { return <div className="mini-timeline"><div className="timeline-marker danger"><AlertTriangle size={14} /></div><div><strong>Incident detected</strong><span>{incident.incident_code} · {formatDate(incident.detected_at)}</span></div></div> }
export function PaymentJourney({ transitions }: { transitions: Transition[] }) { return <div className="payment-journey">{transitions.map((item, index) => <div className="journey-item" key={item.id}><div className={`journey-node ${index === transitions.length - 1 ? 'current' : ''}`}><CircleDot size={15} /></div><div><strong>{titleCase(item.to_state)}</strong><span>{formatDate(item.occurred_at)} · event {item.financial_event_id.slice(0, 8)}</span></div>{index < transitions.length - 1 && <div className="journey-line" />}</div>)}</div> }
export function InvestigationPanel({ result }: { result: Investigation }) { return <section className="investigation-panel"><div className="panel-heading"><div><span className="eyebrow"><Sparkles size={14} /> EVIDENCE-BACKED INVESTIGATION</span><h2>{result.root_cause}</h2></div><div className="confidence"><span>Confidence</span><strong>{Math.round(result.confidence * 100)}%</strong></div></div><div className="investigation-summary">{result.summary}</div><div className="finding-grid"><div><h4>Observed facts</h4>{result.observed_facts.length ? result.observed_facts.map((item) => <p className="fact" key={item}><Check size={14} />{item}</p>) : <p className="muted">No provider-backed facts returned.</p>}</div><div><h4>Derived findings</h4>{result.derived_findings.length ? result.derived_findings.map((item) => <p className="finding" key={item}><Sparkles size={14} />{item}</p>) : <p className="muted">No derived findings returned.</p>}</div></div><div className="impact-strip"><div><span>Financial impact · human-readable</span><strong>{formatMinorCurrency(result.financial_impact_minor)}</strong><small>{rawMinorLabel(result.financial_impact_minor)}</small></div><div><span>Unresolved amount · human-readable</span><strong>{formatMinorCurrency(result.unresolved_amount_minor)}</strong><small>{rawMinorLabel(result.unresolved_amount_minor)}</small></div><div><span>Recommended action</span><strong>{result.recommended_action}</strong></div></div>{result.uncertainties.length > 0 && <div className="uncertainty"><AlertTriangle size={16} /><div><strong>Uncertainty surfaced</strong>{result.uncertainties.map((item) => <p key={item}>{item}</p>)}</div></div>}</section> }
export function PolicyDecision({ decision }: { decision: PolicyDecision | null }) { if (!decision) return <div className="muted">No policy evaluation available.</div>; return <div className="policy-box"><div><LockKeyhole size={18} /><strong>{decision.outcome.replaceAll('_', ' ')}</strong></div><p>{decision.reason}</p></div> }
export function ApprovalControls({ onApprove, onReject }: { onApprove: () => void; onReject: () => void }) { return <div className="action-controls"><button className="button primary" onClick={onApprove}><Check size={16} />Approve</button><button className="button ghost danger-button" onClick={onReject}><X size={16} />Reject</button></div> }
export function ActionCard({ action, onApprove, onReject, onExecute, onVerify }: { action: Action; onApprove?: () => void; onReject?: () => void; onExecute?: () => void; onVerify?: () => void }) { const approval: Approval | undefined = action.approvals.at(-1); const execution = action.executions.at(-1); const canExecute = action.status === 'APPROVED' && !execution; const canVerify = !canExecute && execution?.status === 'EXECUTED' && !execution.verified_at; const verified = execution?.verified_at != null; return <article className="action-card"><div className="action-top"><div><span className="eyebrow">{titleCase(action.action_type)}</span><h3>{action.description}</h3></div><StatusBadge value={action.status} /></div><div className="action-meta"><span><b>Amount</b>{formatMoney(action.amount, action.currency ?? 'INR')}</span><span><b>Confidence</b>{action.confidence === null ? '—' : `${Math.round(action.confidence * 100)}%`}</span><span><b>Approval</b>{approval ? titleCase(approval.status) : 'Not requested'}</span><span><b>Execution</b>{execution ? (execution.status === 'FAILED' ? 'Failed' : verified ? 'Verified' : execution.status) : 'Not started'}</span></div><PolicyDecision decision={action.policy_decision} />{action.requires_approval && action.status === 'PROPOSED' && onApprove && onReject && <ApprovalControls onApprove={onApprove} onReject={onReject} />}{canExecute && onExecute && <div className="action-controls"><button className="button primary" onClick={onExecute}><Play size={16} />Execute</button></div>}{canVerify && onVerify && <div className="action-controls"><button className="button primary" onClick={onVerify}><ShieldCheck size={16} />Verify</button></div>}{verified && <div className="verified-banner"><ShieldCheck size={16} /><span>Verified — incident control no longer triggers.</span></div>}</article> }
export function AuditTimeline({ events }: { events: AuditEvent[] }) { return <div className="audit-list">{events.map((event) => <div className="audit-event" key={event.id}><div className="audit-dot" /><div><strong>{titleCase(event.action_type)}</strong><span>{event.actor_type} {event.actor_id ? `· ${event.actor_id}` : ''} · {formatDate(event.created_at)}</span><p>{event.reason ?? 'No reason recorded.'}</p></div></div>)}</div> }